language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"

git:
  depth: 50

sudo: required

env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6.9

#services:
#  - docker

before_install:
  - docker run hello-world
  - docker --version
  - sudo apt-get update
  - ldd --version
  - gcc --version
  - export START=$(pwd)
  - export REV=$(git describe)
  - export VERSION=$(echo $REV | tr - .)
  # Doscker-specific
  #- sudo apt-get upgrade lxc-docker
  #- echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  #- sudo service docker restart
  #- sleep 5
  #- sudo docker pull centos:centos${OS_VERSION}
  #- sudo docker pull ${OS_TYPE}:${OS_TYPE}${OS_VERSION}
  #- echo "A"



#script:
#  - echo 1
#  - sudo docker run --rm=true -v `pwd`:/tofu:rw centos:centos${OS_VERSION} /bin/bash -c "nosetests --nocapture -v --with-id --with-timer tofu.tests.tests01_geom"
#  - echo 2

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      export VADD="py27";
      export PCK="polygon2";
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      export VADD="py36";
      export PCK="polygon3";
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build
  - conda update -q conda
  - conda update -n root conda-build
  - conda config --set anaconda_upload no
  - conda config --append channels conda-forge
  - conda config --append channels tofuproject
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda install -q python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython nose pip anaconda-client conda-build
  #- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython nose
  #- source activate test-environment
  # If you support official conda packages for your project, you may want to use conda build in Travis, so the building of your recipe is tested as well.
  # replace the following line:
  #- python setup.py develop
  # with:
  # Build params
  # Building
  - conda build conda_recipe
  - export PKG_DIR=$HOME/miniconda/conda-bld/linux-64/
  - conda install tofu --use-local

script:
  - cd $HOME
  #- ls $HOME/miniconda/envs/test-environment/lib/python3.6/site-packages/tofu/geom
  - nosetests --nocapture -v --with-id --with-timer tofu.tests.tests01_geom

after_success:
  - chmod +x $START/anaconda_upload.sh
  #- source deactivate



before_deploy:
  - ls $START
  - cd $START

deploy:
  - provider: pypi
    user: "Didou09"
    password:
      secure:"sIYghJguUkjJVurJirykyVqpXh3RILETvkFsy3eKQDbdrZ3645tz+hqdKMffRqsvM9eaSQ4QTKSv+HmNQgHx5sEOuWOocKUAH9z0Jn6sd55C6WFBq5FgS72NdTJ6GNPM0myKurJce/10A3tLRfQ0cMtJjmmitLhrayz9VWJBeKy3HSirtvWttPYrA1ce7Iewm/7x/tt4jLL27S9n/mPuTNZopHzxgfeaJ2buaaCaXfEvK/H2u+fKxmrPpRBloPVgPBr6HLRAz2udCE/bz6kvT5jttosO18KX90Eqnj335Iqk5lh8kJXTM9ieFNcPb+oETGFIZRV6sJiWPrv8lb3HnFhWLfUXDkorhNGfqxiphwm8jToKO7MoE0Nk7RMQ9G8Y6E80QsxSKriTRN/xlMGJu8649qxnp2hf3CStyU0+HTvfM5x6UKYWT2Av0EGB7dFBap9Rt0yz4V8gwrQeewVog7W4Pp33XmMIYkOTqapsK38LjHlygVKMWMM7WS3EXKXVTTCD8wl6CZ4DwDSnwWm9UyHbYBYrNSkdatmv5yAQrrH/gUEy3AFfBFcP838zAyXOqTl7w/orRM3cKj2ot+btcI3knEP6njsOcczMOoLS/C+4Z2O1w5SqXNQZjGusvusRed+J3ul7mrBrXi2G66KvUieicZwLyqsjwpokwfrcD4c="
    skip_cleanup: true
    on:
      tags: true
      #branch: master
  - provider: script
    user: "ToFuProject"
    script: $START/anaconda_upload.sh
    on:
      tags: true
    skip_cleanup: true
