language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"

# Best because more complete, but too slow
#sudo: enabled

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels alges
  - conda config --add channels conda-forge
  - conda install conda-build
  - conda update -q conda
  - conda update -q conda-build
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython nose
  - source activate test-environment
  
  # If you support official conda packages for your project, you may want to use conda build in Travis, so the building of your recipe is tested as well.
  # replace the following line:
  - python setup.py develop
  # with:
  - export VERSION="""$(python -c "import version; print(version.__version__.replace('-','.'))")"""
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda build ./conda_recipe27/;
    else
      conda build ./conda_recipe36/;
    fi
  #- conda install tofu --use-local



script:
  - nosetests --nocapture -v --with-id --with-timer tests.tests01_geom

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash ./conda_recipe27/conda_upload.sh;
    else
      test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash ./conda_recipe36/conda_upload.sh;
    fi

#deploy:
#  provider: pypi
#  user: "Didou09" 
#  password:
#    secure: 
#  on:
#    tags: true
#    branch: master






