language: python
matrix:
  include:
  - name: Bionic python 3.7
    os: linux
    dist: bionic
    python: 3.7
    env:
    - REPO=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - OS=linux-64
  - name: trusty python 3.6
    os: linux
    dist: trusty
    python: 3.6
    env:
    - REPO=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - OS=linux-64
  - name: xenial python 3.7
    os: linux
    dist: xenial
    python: 3.7
    env:
    - REPO=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - OS=linux-64
  - name: xenial python 3.6
    os: linux
    dist: xenial
    python: 3.6
    env:
    - REPO=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - OS=linux-64
  - name: osx python 3.7
    os: osx
    language: generic
    env:
    - REPO=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    - TRAVIS_PYTHON_VERSION=3.7
    - OS=osx-64
  - name: osx python 3.6
    os: osx
    language: generic
    env:
    - REPO=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    - TRAVIS_PYTHON_VERSION=3.6
    - OS=osx-64
before_install:
- gcc --version
- export START=$(pwd)
install:
- wget "$REPO" -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --append channels conda-forge
- conda config --append channels tofuproject
- conda info -a
- conda install -q python="$TRAVIS_PYTHON_VERSION" conda-verify nose nose-timer coverage
  codecov
- export REV=$(python -c "import _updateversion as up; out=up.updateversion(); print(out)")
- export VERSION=$(echo $REV | tr - .)
- echo $REV
- pip install -e ".[dev]"
script:
- cd $HOME
- nosetests tofu.tests --nocapture -v --with-id --with-timer --with-coverage --cover-package=tofu
after_success:
- codecov
- chmod +x $START/anaconda_upload.sh
- echo $TRAVIS_TAG
before_deploy:
- echo "BEFORE DEPLOY START........"
- ls $START
- cd $START
- conda config --set anaconda_upload no
- conda install anaconda-client conda-build
- conda build conda_recipe
- export PKG_REAL=$(conda build . --output | tail -1)
- echo "BEFORE DEPLOY END.........."
deploy:
  - provider: pypi
    distributions: "sdist"
    user: __token__
    skip_existing: true
    on:
      tags: true
      branch: deploy-test
    server: https://test.pypi.org/legacy/
    password:
      secure: o63EC+U+EtdAgUSV3plrLfZ7QZ6Aflp0quV5jJQxD9w47Ds5i4k5GjEHogV8x8l5NGwxbXPKp/1eKEfYgFH/i+WUnj1n9reiYZBd0lkr2Ih9nExNEIrziMhPbqjDEYAB672bjkXseS6mF44boqDUEP3jyDaamLB+aR75RCMM1j6aha/54Ko88ZJKXBW5FuNSraBGzgvjVG0P63jG5epS85hX09dEcKNR0XO0kbiGfNnYIp78QBohO0Pdv99x2ryp/QaoWD4m7cMUOts2xIcI2KCJNMhZNdIS8C0TVvk2tgumb+G2px7PsOxA8yZgxLefs+A14IAjg6uKe/jmwrihN1V6R6FF3WCcxM6kdzt9bpr+QKBoXjkF8BdxVbgmdnxkr+Ah5WIxmw2boQoW/SIMy9GVPrgtkSvocN6NwOExsO4pagiOwTLIvjIe+/0+OJt/Pud+mwF/94HD+B7j/XxsK7QehLCd9v5NTrdNgpS/TiWOyCDP1DLnpl1V9/vZ56x9NSQhN4Wr6hRrTxjWNAYLxsMxZf6uR+WWg1TqyicVlGrSf0to2asNIPWTTeGq3tB0/7WNslRQzP7QD67p5SuX0Z3Sv0WnQx+rZH77EN6FPCbv8Xn+D4ff06VKHaXXOkiFdK+6pTQ1VmFVPH/ablbWODhhcja/O3Xn3d/zTIyM+oQ=
