language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"

# Best because more complete, but too slow
#sudo: enabled

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      export RECIPE="./conda_recipe27/";
      export VADD="py27_0";
      export PCK="polygon2";
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      export RECIPE="./conda_recipe36/";
      export VADD="py36_0";
      export PCK="polygon3";
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  #- conda config --add channels alges
  #- conda config --add channels conda-forge
  - conda install conda-build
  - conda update -q conda
  - conda update -n root conda-build
  - conda config --add channels pypi
  - conda list
  - pip install -i https://pypi.anaconda.org/pypi/simple $PCK
  - pip install -i https://pypi.anaconda.org/pypi/simple nose-timer
  - conda list
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython nose
  - source activate test-environment
  - conda config --add channels pypi
  - conda list
  - pip install -i https://pypi.anaconda.org/pypi/simple $PCK
  - pip install -i https://pypi.anaconda.org/pypi/simple nose-timer
  - conda list 
  # If you support official conda packages for your project, you may want to use conda build in Travis, so the building of your recipe is tested as well.
  # replace the following line:
  #- python setup.py develop
  # with:
  - export VERSION=$(head -n 1 version.txt)
  - conda build $RECIPE
  #- conda install tofu --use-local



script:
  - nosetests --nocapture -v --with-id --with-timer tests.tests01_geom

after_success:
  - source deactivate
  - if [[ "$((echo $TRAVIS_BRANCH) | head -c 1)" == "v" ]]; then
      conda install anaconda-client;
      bash $RECIPE/conda_upload.sh;
    else
      echo "Not uploaded to conda because not tagged release branch !";
    fi

#deploy:
#  provider: pypi
#  user: "Didou09" 
#  password:
#    secure: 
#  on:
#    tags: true
#    branch: master






