language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"

git:
  depth: 100

sudo: required

before_install:
  - sudo apt-get update
  - ldd --version
  - gcc --version
  - export START=$(pwd)
  - export REV=$(git describe)
  - export VERSION=$(echo $REV | tr - .)

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      export VADD="py27";
      export PCK="polygon2";
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      export VADD="py36";
      export PCK="polygon3";
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build
  - conda update -q conda
  - conda update -n root conda-build
  - conda config --set anaconda_upload no
  - conda config --append channels conda-forge
  - conda config --append channels tofuproject
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda install -q python=$TRAVIS_PYTHON_VERSION conda-build anaconda-client nose nose-timer coverage codecov
  # Building
  - conda build conda_recipe
  - export PKG_DIR=$HOME/miniconda/conda-bld/linux-64/
  - conda install tofu --use-local

script:
  - cd $HOME
  #- ls $HOME/miniconda/envs/test-environment/lib/python3.6/site-packages/tofu/geom
  - nosetests tofu.tests.tests01_geom --nocapture -v --with-id --with-timer --with-coverage --cover-package=tofu

after_success:
  - codecov
  - chmod +x $START/anaconda_upload.sh
  #- source deactivate



before_deploy:
  - ls $START
  - cd $START

deploy:
  - provider: pypi
    user: "Didou09"
    password: ""
    skip_cleanup: true
    on:
      tags: true
      #branch: master
  - provider: script
    user: "ToFuProject"
    script: $START/anaconda_upload.sh
    on:
      tags: true
    skip_cleanup: true
