package:
  name: 'tofu'
  version: {{ environ['VERSION'] }}

source:
  path: ../
  git_rev:  
  git_url: https://github.com/ToFuProject/tofu.git


build:
  - VERSION
  - CONDA_BLD_PATH
  number: {{ GIT_DESCRIBE_NUMBER }} 
  string: {{ GIT_BUILD_STRING }}
  noarch_python: True
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - cython
    - nose
    - nose-timer

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - cython
    - nose
    - nose-timer 

test:
  imports:
    - tofu.geom

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE
  summary: Tomography for Fusion







