package:
  name: 'tofu'
  version: {{ environ['VERSION'] }}

source:
  path: ../
  git_rev:  
  git_url: https://github.com/ToFuProject/tofu.git

build:
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  build:
    - python
    - cpython
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - mpl_toolkits
    - cython
    - nose
    - datetime
    - pygments
    - libc
    - itertools
    - warnings
    - Polygon

  run:
    - python
    - cpython
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - mpl_toolkits
    - cython
    - nose
    - datetime
    - pygments
    - libc
    - itertools
    - warnings
    - Polygon

test:
  imports:
    - tofu.geom

about:
  home: https://github.com/ToFuProject/tofu
  license: MIT
  license_file: LICENSE
  summary: Tomography for Fusion







